# Generated by Django 4.1.7 on 2023-05-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bureau', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bureau',
            name='nationality',
        ),
        migrations.AddField(
            model_name='bureau',
            name='joined_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bureau',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
